name: Create Release
on:
  push:
    tags: ['[0-9]+.[0-9]+*']
  workflow_call:
    inputs:
      ref:
        required: true
        type: string
jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml
    with:
      ref: ${{ inputs.ref || github.ref }}
  create_release:
    name: Create a draft release
    runs-on: 'ubuntu-latest'
    needs: build
    env:
      ref: ${{ inputs.ref || github.ref }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          ref: ${{ env.ref }}
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist-files-3.10
          path: dist
      - name: List dist files
        run: ls -R
        working-directory: dist
      - name: Add environment vars
        run: |
          echo "tag_name=$(basename $ref)" | tee -a $GITHUB_ENV
          echo "PROJECT_VERSION=$(ls -1 dist/pywemo-*.tar.gz | sed -e 's/.*pywemo-\(.*\)\.tar\.gz/\1/')" | tee -a $GITHUB_ENV
          echo "TAG_MESSAGE=$(git tag -l $(basename $ref) --format '%(contents:lines=1)')" | tee -a $GITHUB_ENV
      - name: Check if tag version matches project version
        run: |
          echo "TAG: $tag_name"
          echo "VERSION: $PROJECT_VERSION"
          if [[ "$tag_name" != "$PROJECT_VERSION" ]]; then exit 1; fi
      - name: Generate Checksums
        run: sha256sum pywemo-${PROJECT_VERSION}{-py3-none-any.whl,.tar.gz} > sha256sums.txt
        working-directory: dist
      - name: Create Release Draft
        uses: softprops/action-gh-release@v1
        with:
          name: ${{ env.tag_name }} - ${{ env.TAG_MESSAGE }}
          tag_name: ${{ env.ref }}
          body_path: ".github/RELEASE-TEMPLATE.md"
          generate_release_notes: true
          fail_on_unmatched_files: true
          draft: true
          files: |
            dist/pywemo-${{env.PROJECT_VERSION}}-py3-none-any.whl
            dist/pywemo-${{env.PROJECT_VERSION}}.tar.gz
            dist/sha256sums.txt
