name: Publish
on:
  release:
    types: [published]

permissions: {}

jobs:
  build:
    name: Build
    uses: ./.github/workflows/build.yml

  check:
    name: Check version and tag match
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Download dist artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
      - name: Check if tag version matches project version
        run: |
          BUILD_VERSION="${{ needs.build.outputs.version }}"
          echo "TAG: $GITHUB_REF_NAME"
          echo "VERSION: $BUILD_VERSION"
          if [[ "$GITHUB_REF_NAME" != "$BUILD_VERSION" ]]; then exit 1; fi
      - name: Verify checksums match
        run: echo "${{ needs.build.outputs.hashes }}" | base64 -d | sha256sum -c || exit 1

  slsa:
    name: Generate SLSA provenance
    needs: [build, check]
    permissions:
      # Needed to upload assets to the Github release.
      # TODO: Find a way to remove this:
      #   https://github.com/slsa-framework/slsa-github-generator/issues/2044
      contents: write  
      # Needed to detect the GitHub Actions environment.
      actions: read
      # Needed to create the provenance via GitHub OIDC.
      id-token: write
    uses: slsa-framework/slsa-github-generator/.github/workflows/generator_generic_slsa3.yml@v1.5.0
    with:
      # SHA-256 hashes of the Python distributions.
      base64-subjects: ${{ needs.build.outputs.hashes }}
      # Provenance file name.
      provenance-name: pywemo-${{ needs.build.outputs.version }}.intoto.jsonl

  sigstore:
    name: Generate Sigstore signatures
    needs: [build, check]
    runs-on: ubuntu-latest
    permissions:
      # For Sigstore provenance.
      id-token: write 
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Output hashes
        working-directory: dist
        run: echo "${{ needs.build.outputs.hashes }}" | base64 -d > "pywemo-${{ needs.build.outputs.version }}.sha256sum.txt"
      - name: Sign the release
        uses: sigstore/gh-action-sigstore-python@v1.2.3
        with:
          inputs: ./dist/*
          upload-signing-artifacts: true
          bundle-only: true

  assets:
    name: Publish Release assets
    needs: [build, slsa, sigstore]
    runs-on: ubuntu-latest
    environment: release
    permissions:
      # Needed to run "gh release upload".
      contents: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
      - name: Upload release assets
        env:
          GH_TOKEN: ${{ github.token }}
        run: gh release upload ${{ github.ref_name }} ./${{ needs.slsa.outputs.provenance-name }}/* ./signing-artifacts-sigstore/* --repo ${{ github.repository }}

  pypi:
    name: Publish to PyPi
    runs-on: ubuntu-latest
    needs: [assets]
    environment: release
    permissions:
      # Needed for PyPI trusted publishing.
      id-token: write
    steps:
      - name: Download build artifacts
        uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@v1.8.6
        with:
          repository-url: https://test.pypi.org/legacy/
